### ISSUE TITLE
Building a test script which checks pushed code (CI Pipeline)

### ISSUE THREAD

**Issue by lincolnchia** [DevOps-Team-1-2022/DevOps_Oct2022_Team1_Week4#1]
**Description**
Building a test script which tests the code upon being pushed to github.

**Requirements**
- [x]  Able to run pytest on all files with starting with test_
- [x]  Must be called upon pushing of code 
- [x]  Should be run on latest ubuntu 

**Definition of done** 
- [x]  Script will run upon pushing of code to main
- [x]  Script will return appropriate messages on error 
- [x]  Script will return appropriate messages on success

**Pull Request**
- https://github.com/DevOps-Team-1-2022/DevOps_Oct2022_Team1_Week4/pull/2

**Comment by chuadongen** [comment]
LGTM
