### ISSUE TITLE
Develop main module

### ISSUE THREAD

**Issue by lincolnchia** [DevOps-Team-1-2022/DevOps_Oct2022_Team1_Week4#3]
**Description**
Develop a main module that would call and use the created Hello world module 

**Requirements**
- [x]  Hello world module must be imported and used

**Definition of done**
- [x]  Return expected message output

**Pull Request**

1. https://github.com/DevOps-Team-1-2022/DevOps_Oct2022_Team1_Week4/pull/6

**Comment by chuadongen** [comment]
LGTM
