### ISSUE TITLE
Develop Hello World module

### ISSUE THREAD

**Issue by NPLeeWenKang** [DevOps-Team-1-2022/DevOps_Oct2022_Team1_Week4#4]
**Description**
Develop a hello world module that will return a string based on inputs

**Requirements**
- [x]  Accept string value as a parameter 
- [x]  If chat > 10 or is empty, `Input string too long!`.
- [x] Else return, return  `Hello "+name+"! Welcome to Hello World File!`.

**Definition of done**
- [x]  Return expected message output

**Pull Request**

1. https://github.com/DevOps-Team-1-2022/DevOps_Oct2022_Team1_Week4/pull/5

**Comment by chuadongen** [comment]
LGTM
