### ISSUE TITLE
Develop testcase for Hello World module

### ISSUE THREAD

**Issue by NPLeeWenKang** [DevOps-Team-1-2022/DevOps_Oct2022_Team1_Week4#7]
**Description**
Develop testcase for the Hello World module. Refer to teams for functional test cases

**Requirements**
- [x] test valid string
- [x] test invalid string (>10 char)
- [x] test invalid string (empty string)

**Definition of done**
- [x]  all pytest test passes

**Pull Request**

1. https://github.com/DevOps-Team-1-2022/DevOps_Oct2022_Team1_Week4/pull/8

**Comment by chuadongen** [comment]
LGTM
